apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: omaml
  name: redisserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redisserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: redisserver
    spec:
      containers:
      - env:
        image: gcr.io/google_containers/redis:v1
        imagePullPolicy: ""
        name: redisserver
        resources:
          limits:
            cpu: "1"
            memory: "2097152e3"
        volumeMounts:
        - mountPath: /data
          name: redisdata
        - mountPath: /var/lib/redis
          name: redisdata
        - mountPath: /usr/local/etc/redis/redis.conf
          name: redisdata
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: redisdata
        persistentVolumeClaim:
          claimName: redisdata-claim
