apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: autokeras
  name: autokeras
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: autokeras
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: autokeras
    spec:
      containers:
      - env:
        - name: RUNTIME
          value: "DOCKER"
        image: alexhda/omaml-autokeras
        imagePullPolicy: ""
        name: autokeras
        ports:
        - containerPort: 1433
        resources:
          limits:
            cpu: "2"
            memory: "2097152e3"
        volumeMounts:
        - name: omaml
          mountPath: /omaml
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: omaml
        persistentVolumeClaim:
          claimName: omamldata-claim
