apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: controller
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: controller
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: controller
    spec:
      containers:
      - env:
        image: alexhda/omaml-controller
        imagePullPolicy: ""
        name: controller
        ports:
        - containerPort: 1433
        resources:
          limits:
            cpu: "1"
            memory: "1097152e3"
        volumeMounts:
        - name: datasets
          mountPath: /app/app-data/datasets
        - name: autokeras-output
          mountPath: /app/app-data/output/autokeras
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets-claim
      - name: autokeras-output
        persistentVolumeClaim:
          claimName: output-autokeras-claim
