apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: omaml
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mongodb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - cai-omaml-main
      containers:
      - image: mongo
        name: mongodb
        command: ['mongod']
        env:
        - name: "MONGO_INITDB_ROOT_USERNAME"
          value: "root"
        - name: "MONGO_INITDB_ROOT_PASSWORD"
          value: "example"
        resources:
          limits:
            cpu: "1"
            memory: "2097152e3"
        volumeMounts:
        - mountPath: /data/db
          name: mongodb
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mongodb
        persistentVolumeClaim:
          claimName: mongodb-claim
