apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: autokeras
  name: autokeras
spec:
  type: ClusterIP
  ports:
  - name: "50101"
    port: 50101
    protocol: TCP
    targetPort: 5002
  selector:
    io.kompose.service: autokeras
status:
  loadBalancer: {}