apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: autokeras
  name: autokeras
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: autokeras
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: autokeras
    spec:
      volumes:
      - name: omamldata-pvc
        persistentVolumeClaim:
          claimName: omamldata-claim
      containers:
      - env:
        volumeMounts:
        - name: omamldata-pvc
          mountPath: /omaml
        image: alexhda/omaml-autokeras
        imagePullPolicy: ""
        name: autokeras
        ports:
        - containerPort: 1433
        resources:
          limits:
            cpu: "2"
            memory: "2097152e3"
      restartPolicy: Always
      serviceAccountName: ""
status: {}
