apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: controller
  name: controller
spec:
  type: ClusterIP
  ports:
  - name: "50101"
    port: 50101
    protocol: TCP
    targetPort: 5001
  selector:
    io.kompose.service: controller
status:
  loadBalancer: {}