apiVersion: v1
kind: Service
metadata:
  namespace: omaml
  labels:
    io.kompose.service: sqlserver
  name: sqlserver
spec:
  ports:
  - name: "1533"
    port: 1533
    targetPort: 1433
  selector:
    io.kompose.service: sqlserver
status:
  loadBalancer: {}
